# Generated by Django 5.0.6 on 2024-06-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgCategorias')),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='imgProductos')),
                ('nombre', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ventas', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('largo_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_planchas', models.IntegerField(default=0)),
                ('cantidad_tornillos', models.IntegerField(default=0)),
                ('cantidad_manillas', models.IntegerField(default=0)),
                ('cantidad_bisagras', models.IntegerField(default=0)),
                ('cantidad_patas_gomas', models.IntegerField(default=0)),
                ('cantidad_rieles', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capibara.categoria')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capibara.mueble')),
            ],
        ),
    ]
