# Generated by Django 5.0.6 on 2024-06-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capibara', '0002_boleta_cargo_detalleboleta_opinion_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='nombre_usuario',
            new_name='username',
        ),
    ]
