# Generated by Django 5.0.6 on 2024-06-16 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capibara', '0002_alter_user_email_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to=settings.AUTH_USER_MODEL),
        ),
    ]
