# Generated by Django 5.0.6 on 2024-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capibara', '0003_alter_boleta_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
